### ISSUE TITLE
Tweet を読み込むときにエラーが出る

### ISSUE THREAD

**Issue by huequica** [SawadaReverse/myblog#10]
`Uncaught SyntaxError: Cannot use import statement outside a module` が ChromeDevTools 上 で出力される

おそらく以下の実装が原因

```vue
    head: {
        script: [{
            type: 'text/javascript',
            async: true,
            src: 'https://platform.twitter.com/widgets.js',
            body: true
        }]
    }
```

**Comment by huequica** [comment]
方針: https://www.npmjs.com/package/vue-tweet-embed を使ったら丸っと解決できないだろうか

**Comment by huequica** [comment]
なんか上記モジュールを使って `head` を消しても出てくるので原因は別の可能性があるかも

**Comment by SawadaReverse** [comment]
https://github.com/SawadaReverse/myblog/commit/15a2555025d2031d01edd01e7c22d45523a22f3f  
なんかこれで消えたんだが？  
@huequica 確認してもろていいすか？

**Comment by huequica** [comment]
mdにscriptブチ込むのさすがに行儀わるすぎでしょまあ見るわ

**Comment by SawadaReverse** [comment]
なんか自動で入ったっぽい、入れた覚えがない  
あとこれは別Issueにする予定だけど、AndroidのFirefoxだとTwitterのモジュールが表示されないというのもある

**Comment by huequica** [comment]
確かに問題はPC上では確認されないわね。このチケットは Close で良い気がする

**Comment by huequica** [comment]
とはいえ XSS の脆弱性とか発現されても困るので md をパースした HTML をサニタイズする処理が必要かも
