### ISSUE TITLE
useAsyncの返り値が確実にnullになる

### ISSUE THREAD

**Issue by SawadaReverse** [SawadaReverse/myblog#7]
https://github.com/SawadaReverse/myblog/blob/1220bbba1e5a0344a90cb73e9eaae5cdad965f5d/pages/index.vue#L39-L45
https://github.com/SawadaReverse/myblog/blob/1220bbba1e5a0344a90cb73e9eaae5cdad965f5d/pages/index.vue#L64

記事の取得を非同期で行いたい(というか nuxt/content の `fetch()` が非同期関数なのでそうせざるを得ない)  
ドキュメント通り使ってるはずなのになんで～～～～><

**Comment by moezakura** [comment]
https://github.com/SawadaReverse/myblog/blob/1220bbba1e5a0344a90cb73e9eaae5cdad965f5d/pages/index.vue#L49-L53
↓
```typescript
                return [];
```


https://github.com/SawadaReverse/myblog/blob/1220bbba1e5a0344a90cb73e9eaae5cdad965f5d/pages/index.vue#L68-L72
↓
```typescript
                return 0
```

**Comment by SawadaReverse** [comment]
ちゃんとuseAsyncが解決してくれるまで待ってあげることで解決
