### ISSUE TITLE
謎の generics を虚無に渡してる実装がある

### ISSUE THREAD

**Issue by huequica** [SawadaReverse/myblog#8]
https://github.com/SawadaReverse/myblog/blob/1220bbba1e5a0344a90cb73e9eaae5cdad965f5d/pages/index.vue#L29

こいつのせいで ESLint から parseError が帰る  
<img width="970" alt="Screen Shot 2022-03-31 at 12 00 28" src="https://user-images.githubusercontent.com/40014236/160968569-b5d62cb8-aaa8-4d30-bc57-0db5b41cec1a.png">

**Comment by huequica** [comment]
`route.value.query` の返却値は `Dictionary<string>` もしくは `Dictionary<Array<string | null>>`

**Comment by huequica** [comment]
https://composition-api.nuxtjs.org/packages/routes#useroute

**Comment by SawadaReverse** [comment]
採用
TypeGuardsを使いこなせるようにがんばりますわよ
